version: "3"

services:
  web:
    build:
      context: web
      target: prod
    depends_on:
      - database
    environment:
      REACT_APP_API_URL: "http://localhost:3000"
    ports:
      - 80:80

  api:
    build:
      context: api
      target: prod
    depends_on:
      - database
    environment:
      DB_URL: 'myUrl'
      DB_NAME: 'mooc-db'
      PORT: 3000
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017
    env_file:
      - ./.env
    ports:
      - 3000:3000

  database:
    image: mongo:3.7.9
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
